---
# tasks file for dbserver
- name: Ensure firewalld & python3-firewall are installed
  become: true
  ansible.builtin.package:
    name:
      - firewalld
      - python3-firewall
    state: present

- name: Enable and start firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open mariaDB in firewalld
  become: true
  ansible.posix.firewalld:
    service: mysql
    permanent: true
    state: enabled
    immediate: true
