---
# tasks file for set_password
- name: Set password for deploy
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    password: "{{ deploy_password }}"
    update_password: always

- name: Create sudoers rule with password requirement
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/deploy
    line: "{{ deploy_user }} ALL=(ALL:ALL) ALL"
    state: present
    create: yes
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  
- name: Remove passwordless sudo rule
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/deploy
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    state: absent
    validate: /usr/sbin/visudo -cf %s
