---
- name: Copy https.conf
  hosts: web
  become: true
  tasks:
    - name: Copy from files/https.conf to /etc/nginx/conf.d/https.conf
      ansible.builtin.copy:
        src: files/https.conf
        dest: /etc/nginx/conf.d/https.conf
      register: result

    - name: Jinja template
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Ensure the nginx configuration is updated for example.internal
      ansible.builtin.copy:
        src: files/example.internal.conf
        dest: /etc/nginx/conf.d/example.internal.conf
      register: result

    - name: Setting permissions for /var/www/example.internal/html/
      ansible.builtin.file:
        path: /var/www/example.internal/html
        state: directory
        recurse: true
        seuser: system_u
        serole: object_r
        setype: httpd_sys_content_t
        owner: nginx
        group: nginx

    - name: Copy from files/index.html to /var/www/example.internal/html/index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
      register: result

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: reloaded
      when: result.changed is true
